name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout project sources'
        uses: actions/checkout@v3
      - name: 'Setup java'
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: 'Setup Gradle'
        uses: gradle/gradle-build-action@v2
      - name: 'Run build with Gradle Wrapper'
        run: ./gradlew bootJar
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build the Docker image'
        run: | 
          docker build . --file Dockerfile --tag ghcr.io/max-java/dockerized:1.0.0
          docker push ghcr.io/max-java/dockerized:1.0.0
