name: Variables and triggers testing

on:
  push:
    branches: [ "main" ]
    tags:
      - '*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout project sources'
        uses: actions/checkout@v3
      - name: 'Setup java'
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: 'Setup Gradle'
        uses: gradle/gradle-build-action@v2
      - name: 'Set project version from gradle'
        run: echo "GRADLE_VERSION=$(./gradlew properties -q | grep version | awk '{print $2}')" >> $GITHUB_ENV
      - name: 'Set commit hash'
        run: echo "GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
      - name: 'print variables'
        run: |
          echo GITHUB_REF_NAME  ${GITHUB_REF_NAME}
          echo GITHUB_REF_TYPE  ${GITHUB_REF_TYPE}
          echo GRADLE_VERSION   $GRADLE_VERSION
          echo GIT_HASH         $GIT_HASH
      - name: 'evaluate version'
        run: |
          if [ "$GITHUB_REF_TYPE" == "branch" ]; then
            echo 'use application version from gradle.build file and git hash from commit for image version'
            echo "VERSION=v.$GRADLE_VERSION-$GIT_HASH" >> $GITHUB_ENV
          fi          
          if [ "$GITHUB_REF_TYPE" == "tag" ]; then
            echo 'use git tag for image version'
            echo "VERSION=v.$GITHUB_REF_NAME" >> $GITHUB_ENV
          fi
          echo version is set to $VERSION
      - name: 'print version'
        run: |
          echo version is set to $VERSION
#          git_hash=$(git rev-parse --short "$GITHUB_SHA")
#          echo "GIT_HASH=$(git rev-parse --short '$GITHUB_SHA')" >> $GITHUB_ENV
#          git_branch=${GITHUB_REF#refs/heads/}
#          echo git_hash         $git_hash
#          echo git_branch       $git_branch
#          echo GITHUB_REF_NAME  ${GITHUB_REF_NAME}
#          echo GITHUB_REF_TYPE  ${GITHUB_REF_TYPE}
#          echo GRADLE_VERSION   $GRADLE_VERSION
#          echo GIT_HASH         $GIT_HASH
#      - name: 'Create version'
#        run: |
#          git_hash=$(git rev-parse --short "$GITHUB_SHA")
#          echo GRADLE_VERSION   $GRADLE_VERSION
#          echo GIT_HASH         $GIT_HASH
#          echo git_hash         $git_hash
#          if [ "$GITHUB_REF_TYPE" == "tag" ]; then
#            echo 'use git tag for image version'
#            echo 'version=$GITHUB_REF_NAME'
#
#          fi
#          if [ "$GITHUB_REF_TYPE" == "branch" ]; then
#            echo 'use application version and git commit for image version'
#            git_hash=$(git rev-parse --short "$GITHUB_SHA")
#            project_version=$(./gradlew properties -q | grep version | awk '{print $2}')
#            echo 'VERSION1=$project_version-$git_hash' >> $GITHUB_ENV
#            echo 'VERSION2=$GRADLE_VERSION-$$GIT_HASH' >> $GITHUB_ENV
#          fi
#          echo dockerized:$VERSION1
#          echo dockerized:$VERSION2
#      - name: 'Print version'
#        run: |