name: Variables and triggers testing

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout project sources'
        uses: actions/checkout@v3
      - name: 'print variables'
        run: | 
          echo "Branch: ${{ env.branch }}"
          echo "Sha: ${{ env.sha_short }}"
