name: Variables and triggers testing

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout project sources'
        uses: actions/checkout@v3
      - name: 'print variables'
        run: | 
          echo git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo git_branch=${GITHUB_REF#refs/heads/}
