name: Variables and triggers testing

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout project sources'
        uses: actions/checkout@v3
      - name: 'print variables'
        run: | 
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          git_branch=${GITHUB_REF#refs/heads/}
          echo git_hash         $git_hash
          echo git_branch       $git_branch
          echo GITHUB_REF_NAME  ${GITHUB_REF_NAME}
          echo GITHUB_REF_TYPE  ${GITHUB_REF_TYPE}
